### ISSUE TITLE
Failure to reconnect

### ISSUE THREAD

**Issue by Harmon758** [Shizmob/pydle#51]
I'm using client.run in the asyncio branch, and after a short period of being connected, I'm encountering:

```
Encountered error on socket.
TimeoutError: Ping timeout: no data received from server in 180 seconds.
Unexpected disconnect. Attempting to reconnect.
```

after which the memory for the process jumps from ~15 MB to ~2 GB.
This seems to be because on_data is triggered constantly with empty bytestrings. It's possible this is a result of handle_forever continuing after the connection is disconnected.
I'm not sure what's causing the initial ping timeout though. I'm using a program that was running properly with the master branch, and just converted it by adding async's and await's to overrides and calls of functions that were converted into coroutines and by using client.run instead of client.connect and client.handle_forever

**Comment by Shizmob** [comment]
Holy smokes, that is a problem. I'll at least make sure it doesn't eat your CPU like that.
Are you sure the ping timeout is not just a momentary connection drop?
Thanks for reporting!

**Comment by Harmon758** [comment]
No problem. Thanks for the fix.
I'm now getting:
```
Encountered error on socket.
TimeoutError: Ping timeout: no data received from server in 180 seconds.
Unexpected disconnect. Attempting to reconnect.
Unexpected disconnect. Attempting to reconnect within 5 seconds.
Unexpected disconnect. Attempting to reconnect within 10 seconds.
Unexpected disconnect. Giving up.
```
and normal memory usage, so the memory leak has been fixed.
It doesn't appear to be a connection issue, because I'm consistently encountering it after a short period after connecting. It's possible the server I'm connecting to is not sending a ping within 3 min., because I tried setting PING_TIMEOUT to 300 instead of 180, and I don't seem to be getting the timeout error anymore. Is there a proper way to set this variable without modifying client.py itself?

**Comment by Shizmob** [comment]
I can reproduce the failure to reconnect issue here as well, so I'll look into it later.

I've pushed a commit that moves the `PING_TIMEOUT` variable inside of `pydle.Client`, so you can simply override it in your client subclass now. Thanks for using pydle!

**Comment by Harmon758** [comment]
Thank you for the update.
I was able to do that, and I'm currently not having any more issues with the asyncio branch.
I'll leave this issue open for the reconnect issue.

**Comment by Harmon758** [comment]
It doesn't even reach that point in v0.8.5 now and errors as in #103.
I'm not sure how any ping timeout would not have errored in this way.

**Comment by LiraNuna** [comment]
I am encountering this as well on 0.9.2, I cannot reliably reproduce it, I will report back if I can

**Comment by theunkn0wn1** [comment]
@LiraNuna To be clear, you are encountering a connection timeout that is followed by a massive spike in RAM usage?

If not then your issue is most likely different.

If you are able to reproduce this, please create a new ticket with the following information:
a minimum reproducible example and log output.

**Comment by LiraNuna** [comment]
> @LiraNuna To be clear, you are encountering a connection timeout that is followed by a massive spike in RAM usage?

Sorry I didn't fully read the issue... What I'm getting is a timeout with an unexpected disconnect. Sorry for reviving this without fully reading, I could not find another issue with the same error message.

**Comment by Harmon758** [comment]
This issue *is not* resolved. As I said, I was leaving the issue open for the reconnect issue that's been persistent since at least v0.8.4, and which has not been fixed in the releases that followed: v0.8.5, v0.9.0 (titled incorrectly as v9.0.0 in the GitHub release), and v0.9.1.
I haven't tested v0.9.2 yet, but as none of the changes in that release touch the relevant code, I'm fairly certain the issue still persists in that version as well.

As this thread outlines, the memory issues were resolved in the commit that mentioned this issue, and the ability to set `PING_TIMEOUT` has mitigated the reconnect issue, but the issue with failing to reconnect has been acknowledged as reproducible:
> I can reproduce the failure to reconnect issue here as well

and has not been fixed.

The log output has already been provided in this issue, and the only reproduction steps necessary are to encounter a ping timeout. There doesn't need to be any specific code beyond running a `Client`.
Like I said about the failure to reproduce this issue with v0.8.5, I'm not sure how any attempt to do so would not have encountered a separate issue with ping timeouts (#103) introduced with v0.8.5.

Personally, I had to make further changes locally to mitigate the issue, My fixes at least allow me to reconnect, but I think there's a separate issue where it sometimes doesn't do so properly and causes another disconnect soon afterwards.

That's part of the reason I haven't PR'ed the changes, but to be honest, the main reason is because previous incidents, where my PRs were ignored/closed and then later incorporated into future commits, have made me disinclined to do so. These incidents were just part of the larger recent mishandling of this repository/library, including merging of PRs riddled with bugs, untested releases with major breaking issues, and unprofessionalism, among other problems. The dismissal and closing of this unresolved issue is just another example. I already brought this to @Shizmob's attention at the start of the year, but the lack of action has already prompted me to stop using this library for new projects and start transitioning existing projects to using other libraries. With the closing of this issue and the general lack of activity otherwise, I'll likely finish doing that soon and stop using this library altogether.

**Comment by theunkn0wn1** [comment]
Ok, if it persists in 0.9.1 then you are correct in saying its not resolved. Given the lack of feedback and my inability to reproduce this issue I falsely presumed it had been resolved.

Since 0.8.5 I had done extensive manual testing, doubly so pursuant #103, this ticket, #108, and related.


For reference, i have been testing against a clean UnrealIRCd server as well as a production UnrealIRCd network. The main methods I attempted to reproduce this issue were:
a) using the readme `MyOwnBot` client as-is (short of changing the server it connects to) and using network trickery to introduce a timeout condition
b) using a Modified version of `MyOwnBot` from the readme to invoke Pydle's timeout routine manually via a `on_message` event
c) Using my downstream Pydle client on a production UnrealIRCd network, using a combination of A and B methods

In both cases the bot successfully reconnected to the network. 

What server are are/were you connecting to that caused this issue to manifest?

-------------------
As for the mishandling around 0.8.5/0.9.0:
I agree those releases could have gone smoother, and I had not exercised sufficient due diligence in terms of  knowing when certain language features were released and proper versioning.

------------------------
In relation to 
>PRs riddled with bugs, untested releases with major breaking issues

I test each and every Pull request, and intentionally leave them open for weeks as to acquire comments and feedback. 

The larger issue here is Pydle's lack of a working test suite ( #78 ), something we ( @shatteredbeam and I) have been slowly making progress towards. The biggest issue with implementing a test suite that can detect these kinds of issues before a release is made stems from python's GIL and my inexperience with multiprocessing. We cannot have something like `pytest` submitting coroutines to a Pydle thread, as the GIL will ensure that the Pydle thread (or pytest) is never running concurrently, one must be suspended for the other to execute. Given the nature of Pydle being an IRC client, it tends not to take kindly to being suspended so the `pytest` thread can run.

The only viable solution, I suspect, is to use some form of Multiprocessing setup with some mechanism for the test harness to read from an actual IRC server (for assertions), and also being able to command a Pydle bot (or possibly multiple, for some scenarios) to perform specific actions. Work is slowly being done towards this end.
 


--------------------------

To be honest, in relation to #92 #97 #90 # and possibly others from the same time period:
I felt frustrated by my introduction of >=3.7 language features & related bugs I did not find during testing of 0.8.5/0.9.0 and felt responsible to fix them myself. Further I felt it was unprofessional to immediately file pull requests without giving the project maintainer / the person that introduced the bugs an opportunity to verify/correct the reported issues.

 I appreciated the issues you brought to my attention as a result of my inadequate testing and knowledge of when certain language features were introduced ( #90 #89 #91 #79  ), but I would have also appreciated time to resolve the issues prior to the pull requests.  I strongly suspect that this is simply me not fully understanding the function of open source software, causing unnecessary friction. By no means was I attempting to
>... remade later on to take ... credit.



It is regretful that my actions in this regard, independently developing fixes for the reported issues,  were misconstrued as unprofessional, that was not my intent.

**Comment by LiraNuna** [comment]
I think I have solved the "mystery" of the disconnects. It's this method: https://github.com/Shizmob/pydle/blob/master/pydle/client.py#L162-L175

All it does is sleep for 5 minutes, then forces disconnect without a disconnect. I do not understand why this function exist. Removing this function solved ALL of my "random" disconnect problems.

I could send a PR to remove it (and the call to schedule it).

**Comment by theunkn0wn1** [comment]
That method exists to orchestrate a ping timeout scenario, where the socket to the server remains open but it simply stops talking to us. It should be getting reset whenever we receive anything from the server, If it is not I suspect one of the events are not properly resetting it.

I have encountered this before when extending `pydle.Client.on_message` without ensuring the superclass was called. Can you verify that you are calling the superclass method for any `on_{event}` handlers you may be implementing?

**Comment by theunkn0wn1** [comment]
Went ahead and ran the `echo bot` example in the readme against a quiet (empty) IRC server,
which debunks my `on_{event}` theory as the bot remains properly connected and successfully reconnects when i break the connection. The readme examples don't call the superclass methods. Something else is going on here.

@LiraNuna are you connecting to any specific IRC server in particular?

As a mitigating factor, the sleep period is determined by the `BasicClient.PING_TIMEOUT` class attribute (in seconds), which does default to 5 minutes (300 seconds). This will not fix the issue, but should increase the time between timeouts.

I would be open to a PR that makes this timeout optional (enabled by default), but I believe removing it entirely is improper. The root issue most probably has to do with the `BasicClient.on_data` event, which is responsible for resetting this timer to begin with.

**Comment by dazuling** [comment]
Something to note is that the server may not necessarily send a PING within every `PING_TIMEOUT` seconds if the client has been active. Perhaps an alternative solution is to PING the server before going through with the client disconnect to verify that the server has stopped communicating with the client.

e.g. change https://github.com/Shizmob/pydle/blob/master/pydle/client.py#L170 to

```python
# pause for delay - 1 seconds
await sleep(delay - 1)
# attempt to PING server
await self.raw('PING\r\n')
await sleep(1)
# then continue

**Comment by theunkn0wn1** [comment]
That does seem like a sensible middle ground, and looking at the specifications this is a valid use case. Personally, I would allow several seconds for the ping to go through, when accounting for possible network lag. 

If the client has been active on the server, I would expect to see some data being returned, however this does not appear to be a requirement.

Doing some preliminary testing, we will also need to implement an `on_raw_pong` method so we do not introduce a warning.
```
DEBUG:MyOwnBot:localhost:>> PRIVMSG #bottest ping!

DEBUG:MyOwnBot:localhost:>> PING 127.0.0.1

DEBUG:MyOwnBot:localhost:<< :irc.unknown.com PONG irc.unknown.com :127.0.0.1
WARNING:MyOwnBot:localhost:Unknown command: [irc.unknown.com] PONG ['irc.unknown.com', '127.0.0.1']
```

**Comment by LiraNuna** [comment]
> That method exists to orchestrate a silent timeout scenario

asyncio should be throwing a `TimeoutException` when that happens. In other words, the operation system should notify you about that since you should be connected via TCP. 

And even if it does happen, why does it not attempt to reconnect? It just disconnects and spews the stack trace. I have been using that fix for around 3 days now and things have been very stable so far.

> @LiraNuna are you connecting to any specific IRC server in particular?

I'm connected to `irc.mzima.net` and it reliably disconnects. 

> I have encountered this before when extending pydle.Client.on_message without ensuring the superclass was called. Can you verify that you are calling the superclass method for any on_{event} handlers you may be implementing?

This was not in the docs or specified anywhere, even the readme is showing this as "example usage": https://github.com/Shizmob/pydle/blame/master/README.md#L38-L41 so I did not call it. If that will solve it I can be satisfied, but I firmly think the ping timeout loop should not be needed, as TCP will handle this for you.

**Comment by LiraNuna** [comment]
@dazuling's suggestion is correct - the client should send a PING to the server and expect a reply, if a reply is not received, a timeout will occur and the connection will be terminated - All as a part of the underlying protocol (TCP).

**Comment by theunkn0wn1** [comment]
> This was not in the docs or specified anywhere, even the readme is showing this as "example usage": 

sorry that was actually just me recalling incorrectly. It is not a requirement and is not documented.
After i made that comment I went to verify if that was correct , [and it appears i was mistaken](https://github.com/Shizmob/pydle/issues/51#issuecomment-519343009)

As for why this timeout mechanism exists, I am not entirely certain. looking through previous issues filed on this repo, #38 [comment](https://github.com/Shizmob/pydle/issues/38#issuecomment-240220000) suggests 
> did not want a pydle client to time-out willy nilly if someone's TCP connectivity dropped for a few minutes
TCP's job in all this is to keep the socket between Pydle and the Server alive, I suspect this timeout routine was implemented for scenarios where the socket remains valid, ie the TCP transport is still working, but the server decides not to actually communicate with our client. a simple irc `PING` command sent from the client should suffice into proving the server still wants to talk, but simply has nothing to say.

> And even if it does happen, why does it not attempt to reconnect? 
It should do, if its not reconnecting we have a bug. 


I am presently connected to `irc.mzima.net` and it does appear to send `PING` commands to the client periodically, if not very infrequently. This is probably the root cause of your issue @LiraNuna .

@dazuling is actually suggesting issuing a PING at the irc protocol level, rather than doing anything with the underlying TCP transport. Doing a quick test against this IRC server indicates it does quickly respond to ping requests (as it should, as per the spec), which does trigger the `on_data` event which will cancel the timeout sequence.

**Comment by LiraNuna** [comment]
> @dazuling is actually suggesting issuing a PING at the irc protocol level, rather than doing anything with the underlying TCP transport.

Yeah, and I agree with it - attempting to send data will force the socket to re-evaluate the state of the connection which will either re-establish a connection automatically or at the worse case, disconnect with a `TimeoutException`.

Essentially, I think that "ping check" wait is unnecessary.

**Comment by theunkn0wn1** [comment]
If we do not wait, the `self.on_data_error` will be called immediately which is undesirable. The "ping check " wait is to give the server time to respond and for this routine to be canceled.

**Comment by LiraNuna** [comment]
I should've been more clear - I mean the "wait for a ping loop" is unnecessary. @dazuling's suggestion should only exist in "extreme" situations where the client doesn't hear from the server in a relatively long time (I don't think 5 minutes is considered a long time) and since in many cases the TCP protocol layer will make sure the connection is alive, the act of sending a ping isn't really necessary.

All in all, this isn't my library, I'm just a user, and as long as things work for me (read as: random disconnections stop) I'm happy, even if something behind the scenes is a little redundant/inefficient - as long as it doesn't cause any future issues.

Remember that every bit of unnecessary code has the potential to cause bugs, just like the loop currently causes bugs in some servers such as mzima. Who knows, maybe the ping behavior will not work on others?

**Comment by theunkn0wn1** [comment]
Ahh, my apologies, I totally misinterpreted what you were saying. 

In a perfect world this routine wouldn't even be necessary, as everything would just /work/. 

I just did some digging into why this timeout routine was implemented the way it was, and found this commit:
f223f15575777588f4ac7e726524d380183e44ec

At one point this solution was already in the codebase, it was removed as its non-compliant with RFC1459

Citing the relevant portion,[ 4.6.2](https://tools.ietf.org/html/rfc1459#section-4.6.2), 
```
  Servers should not respond to PING commands but rely on PINGs from
   the other end of the connection to indicate the connection is alive.
   If the <server2> parameter is specified, the PING message gets
   forwarded there.
```

**Comment by LiraNuna** [comment]
Any progress on this? I'd send you a PR to completely remove the method because that's what solves the issue for me.

I think to handle it correctly, you'd need to wrap sends and receives with a try/except to catch any `TimeoutError`s and reconnect on those. What would you think of that solution instead? I don't this it makes sense to attempt to predict how long the server will PING you

**Comment by theunkn0wn1** [comment]
Sorry, had been caught up with work and hadn't been able to thoroughly test the ping solution yet.

I don't think removing this routine entirely is a good idea, to prevent a regression of #13.

Seems some ircds do respond to server pings, including `irc.mzima.net` and unrealircd so 
9f50f04 should help. At the very least sending anything on the socket should cause the socket to be re-evaluated.

the `read()` call on an asynco connection unfortunately does not accept a timeout argument, it will block indefinitely. 
`send()` routines shouldn't block, and would raise an exception if the socket went bad. 
Given the ping frequency on a given ircd is configurable (or at least it is using unrealircd), I am suspecting check as it is currently implemented is flawed.

At worst, i think this routine should at worst raise a warning, rather than disconnect the client. 

What do you think about exposing it as an event on the client's interface like we do with other irc events, allow downstream implementations to choose what they want to do?

The default behavior should remain as the disconnect, to preserve reverse-compatibility.

**Comment by LiraNuna** [comment]
But there is no disconnection, at least on the mzima part. It should be
misleading to give a disconnection event in this event.

Also, you could use `asyncio.wait_for` for a timeout, just remember that
there read will be cancelled as a result.
Although, if there is legitimately no data to be read, it doesn't mean that
there has been any disconnection. Maybe do send a ping?

**Comment by theunkn0wn1** [comment]
So the reasoning behind this routine is something to the effect of:
"we haven't heard from the server in too long, its probably no there anymore and forgot to clean up its socket..." 
Pydle assumes based on the fact its heard nothing for too long that its disconnected, rather than depending on the remote party to close the connection. Pydle could do a better job of communicating *why* its disconnecting in the logging output, 


I was not aware of `asyncio.wait_for`, this would negate the need for this manual timeout routine entirely, as the TimeoutError can be handled in place. Looking at the documentation, it has been present in asyncio long enough not to pose compatibility issues with Pydle's supported interpreter versions.

Given `asyncio.wait_for`, I believe the proper fix would indeed to remove the task in question as its not needed and handle the timeout in `pydle.client.handle_forever`. 

What do you think of the idea of exposing the timeout handling code as an over-writable event?

**Comment by LiraNuna** [comment]
> What do you think of the idea of exposing the timeout handling code as an over-writable event?

I think that it's a good idea as long as there's a sane default behaviour, which imo is, send a ping to the server with a long enough timeout and let the transport layer do it's thing. In case of an error reconnect (currently it DISCONNECTS)

**Comment by theunkn0wn1** [comment]
I concur. it disconnecting without attempting to reconnect in this mode isn't a sane default behavior.

**Comment by LiraNuna** [comment]
Is there a way right now to listen to disconnects? so that clients may choose to reconnect themselves? Was that what you were suggesting?

**Comment by theunkn0wn1** [comment]
there is, `Client.on_disconnect(expected:bool)`

**Comment by theunkn0wn1** [comment]
In fact, pydle clients could just listen to that event, we don't need a new callback for this.

**Comment by LiraNuna** [comment]
I think that's acceptable then, leave the reconnection burden on to the client. I can send a PR later today if you'd like

**Comment by theunkn0wn1** [comment]
I would welcome such a PR.

**Comment by LiraNuna** [comment]
> At one point the proposed solution was already in the codebase, it was removed as its non-compliant with RFC1459

I think this is a misinterpretation of the spec... reading it IN CONTEXT I think it means something like "servers should not respond to PING commands THAT ARE DIRECTED AT OTHER USERS, they should FORWARD THE REPLY from the client"

```

   Any client which receives a PING message must respond to <server1>
   (server which sent the PING message out) as quickly as possible with
   an appropriate PONG message to indicate it is still there and alive.
   Servers should not respond to PING commands but rely on PINGs from
   the other end of the connection to indicate the connection is alive.
   If the <server2> parameter is specified, the PING message gets
   forwarded there.```

servers use PING among themselves to let nodes know they are alive, there's even an example of that: 
```
   PING tolsun.oulu.fi             ; server sending a PING message to
                                   another server to indicate it is still
                                   alive.
```

Given that, I think we SHOULD expect servers to reply to PINGs that **are directed to them** (as opposed to **pings that are directed to other clients**). Thoughts?
