### ISSUE TITLE
client.whois() seems case sensitive

### ISSUE THREAD

**Issue by bigfoot547** [Shizmob/pydle#65]
If there was a user named "user" on IRC and I used `client.whois` on them like so:
```python
client.whois("USER")
```
the whois would never be completed because it seems `whois` is scanning for whois lines from a user named "USER" not "user".

Main questions:
- Is this just a problem with how I am using pydle?
- Is this functionality intentional?
- Can it be fixed?

**Comment by rfw** [comment]
This is definitely not intentional functionality: the names being WHOISed should be normalized.

I think the appropriate fix should be a change to pydle/features/rfc1459/client.py by replace `pending['whois']`/`pending['whowas']` with `parsing.NormalizingDicts({}, self._case_mapping)`. I don't have time to test this, unfortunately: could you try the change?
